### ISSUE TITLE
On OSX flycheck messages show up on the monitor where the mouse cursor is

### ISSUE THREAD

**Issue by carloscheddar** [flycheck/flycheck-pos-tip#15]
Using OSX `flycheck` popup messages for errors and warnings show up on the `monitor` that has the `mouse cursor` instead of only displaying on top of the spacemacs window.

You can see more information about this issue here: https://github.com/syl20bnr/spacemacs/issues/4595

**Comment by lunaryorn** [comment]
@carloscheddar I've failed to reproduce this issue, using a regular homebrew build of Emacs 25.1.  No matter where my mouse cursor is, the tooltip always appears right below the point (i.e. the Emacs cursor).

Would you tell me your Emacs version and your OS X version?

**Comment by carloscheddar** [comment]
I'm running OS X El Capitan and a port of Emacs 24.5.1 https://github.com/railwaycat/homebrew-emacsmacport
Also just to be clear this happens when I run it in a GUI.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.8
- Spacemacs branch: master (rev. ef5a2ad)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp dockerfile git markdown html ruby org javascript syntax-checking yaml)
```

**Comment by lunaryorn** [comment]
@carloscheddar Could you show me the value of `pos-tip-use-relative-coordinates` in your Emacs?

**Comment by lunaryorn** [comment]
@carloscheddar Being unable to reproduce the issue I'm fishing in muddy waters; I have pushed a change which explicitly passes the coordinates of the frame to `pos-tip`, based on an uneducated guess of what could probably cause this issue :blush:

I'd appreciate if you could test the next MELPA build of this extension to see whether the problem disappears.  I can't promise anything, though :relaxed:

**Comment by lunaryorn** [comment]
Were you able to test the fix?

**Comment by carloscheddar** [comment]
I updated all packages today and tested the fix but it's still happening. Let me know if I can provide any more information about this.

**Comment by lunaryorn** [comment]
@carloscheddar Could you try to reproduce the issue in normal GNU Emacs?

**Comment by aaronjensen** [comment]
I can reproduce this if I use a window manager like slate to move the window. It doesn't happen every time, but occasionally the tooltip will appear in the wrong place after a movement.

**Comment by thornjad** [comment]
After being bothered by this for a long time, I forked this package and tried to fix it myself. Despite being able to consistently reproduce this, I can't figure out a fix. I hate recommending other packages on issues, but switching to [flycheck-popup-tip](https://github.com/flycheck/flycheck-popup-tip) works perfectly out of the box on MacOS for me, and claims to work better in TUI as well. 

It looks like this is the route taken by Doom as well: doomemacs/doomemacs#318
